spring.application.name=TradeLedger

# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5433/puja_hardware
spring.datasource.username=postgres
spring.datasource.password=DronaPay_1142
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# 3. Logging & Port
server.port=8080
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=INFO

