spring.application.name=TradeLedger

# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5433/puja_hardware
spring.datasource.username=postgres
spring.datasource.password=DronaPay_1142
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# 3. Logging & Port
server.port=8080
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=INFO

# WhatsApp Config
whatsapp.api.url=https://graph.facebook.com/v18.0
whatsapp.phone.number.id=1131568116700462
whatsapp.access.token=EAAXjQQPxiWUBRDTAZC42Cvg3S5ZAekDLq0rc7M6srXLl3T1Gb7itZBljbQH7yhjtuoHsRtHQZBGZA3uxdwTSi7KUmtHNCUMyijdmrnHUixcm41fjBRIjGNj5ZCHE8KgfSdENPExR4crRbIYAVIMCSHLrAF8vqv0I8dKs15ECJ8PeTh1JTdnMWe9LtWkRY11QJ7Fm1r6LU7lCxJftG79Qbo8s9D7TeOweZAvKCXAUAX4wd8ZCc76X8o4po0aqxzlTGSexUN0WPYPlQO7QZCNcOvlZCC

# PDF storage
pdf.storage.path=/tmp/bills/

# CORS Properties
cors.allowed.origins=http://localhost:5173